### ISSUE TITLE
关于  '每天25分钟智慧树, 健康生活50年, 幸福生活一辈子'

### ISSUE THREAD

**Issue by wdssfff** [notnotype/zhihuishu-cli#10]
想翻mirai的命令来着，
突然看到这25分钟的话
大佬可以考虑下加入每天按时执行视频观看
然后看够25分钟（或者26分钟）然后自动暂停任务86400s
之后继续看下去，如果该视频看完却不到25分钟则自动继续下一个视频
来实现满足平时分的前提下自动挂机

**Comment by notnotype** [comment]
# 已经有了 
看 run-course 命令
你还可以实现自己的 Course Worker(deploy 命令)

**Comment by notnotype** [comment]
https://github.com/notnotype/zhihuishu-cli#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%83%A8%E7%BD%B2

**Comment by wdssfff** [comment]
哦哦，了解了
