### ISSUE TITLE
使用定时学习，它的观看视频的顺序时随机的

### ISSUE THREAD

**Issue by guoluyuan** [notnotype/zhihuishu-cli#11]
使用定时学习，它的观看视频的顺序时随机的，没有按照顺序观看，还有不知道它是否跳过已经观看的视频

**Comment by notnotype** [comment]
它是按顺序播放的

**Comment by notnotype** [comment]
看这段代码 https://github.com/notnotype/zhihuishu-cli/blob/682fbdf1ed59603481adfe900eaf3d9509a16d62/deploy.py#L83

**Comment by guoluyuan** [comment]
又出一个问题，学习完去电脑端或手机端查看，进度没有变化，有增加播放视频节数但是视频后面没有打勾，在电脑或者手机上播放都有打勾记录

**Comment by notnotype** [comment]
可能还有最后一点没看完，在手机上看完就可以了
