### ISSUE TITLE
无法获取token并填入.zhihuishurc

### ISSUE THREAD

**Issue by 19819068211** [notnotype/zhihuishu-cli#13]
运行python zhihuishu-cli.py auth后，无法获取token并填入.zhihuishur
![屏幕截图(20)](https://user-images.githubusercontent.com/66981884/140263215-e659dc46-9990-494a-ba75-1e7228e0ad98.png)

**Comment by notnotype** [comment]
安装chrome设置为默认浏览器，另外现在好像不需要token也可以使用了
