### ISSUE TITLE
扫码后报错，手机提示登录成功，程序提示登录失败，未知错误

### ISSUE THREAD

**Issue by 19819068211** [notnotype/zhihuishu-cli#3]
作者大大，运行python zhihuishu-cli.py share-course命令并扫码后报错，提示登录失败，未知错误
![IMG_20210807_144119](https://user-images.githubusercontent.com/66981884/128591577-09388049-f304-40cd-aad3-ed5ce2882354.jpg)
![Screenshot_20210807_144101_com able wisdomtree](https://user-images.githubusercontent.com/66981884/128591578-5c36c0fb-50d9-456c-9c68-4e65debff549.jpg)

**Comment by notnotype** [comment]
智慧树接入了阿里云的滑动验证码：

![Snipaste_2021-08-08_11-47-44](https://user-images.githubusercontent.com/53962334/128620064-2300f930-47f5-4216-8f2d-d28079c5c357.png)

滑动完验证码后，登录界面的url会由
`https://passport.zhihuishu.com/login?service=https%3A%2F%2Fonlineservice.zhihuishu.com%2Flogin%2Fgologin`
变成：
`https://passport.zhihuishu.com/login?service=https%3A%2F%2Fonlineservice.zhihuishu.com%2Flogin%2Fgologin&u_atype=4&u_atoken=a60009e5-ec23-4ece-bfbe-6038762e0bfc&u_asession=01JTYfvSxRUJuHzT3Y3xKunRlFP0aWajcUApTd5P6Wb6MOwh1_2UJrPCy5i00uof7EX0KNBwm7Lovlpxjd_P_q4JsKWYrT3W_NKPr8w6oU7K8iS5zFFYizaDlgDw2W8feS4IWA3FbkL9vSUgJpwLOuBfJ9EHXfqFOxCyFBuG8Ag_c&u_asig=05VgVhNIzLPDHNnMYTEt2anq-DByFL568KESxXeL_3qvvb1cOf_zUfvnnYdityr7AZlLocTCvAXUH6StMqFRRSVqSxcTSkh8C0FCnyD593j_k50N8duSlrfQQQApm1Yhozv0y3ESyDWX-n4laIgPAy7LMMfY6LqtNJfDhi4KxrOcg7ozFsiUGsVAeSTqoZj3OT63Fl_12JOJ9D6CNoGHzLuVPChqJ45H8zfETAmI9FhFnGGoVpzW6QMhhSDbc5e_qWx7JHN_nWtA4lWCw6r1cmcxMGBWjTmEDMQKJ9PW6HWBE5v_rvt_8YTqQXP_TRcMqX3TbrNDfGSvQQXslQnDkz0zTXUT_zIvOVn_4BTwbi2CMNOtJ2Aq4b96o7yH-2uQ3D`

把`&u_atype`后面这一段

`&u_atype=4&u_atoken=a60009e5-ec23-4ece-bfbe-6038762e0bfc&u_asession=01JTYfvSxRUJuHzT3Y3xKunRlFP0aWajcUApTd5P6Wb6MOwh1_2UJrPCy5i00uof7EX0KNBwm7Lovlpxjd_P_q4JsKWYrT3W_NKPr8w6oU7K8iS5zFFYizaDlgDw2W8feS4IWA3FbkL9vSUgJpwLOuBfJ9EHXfqFOxCyFBuG8Ag_c&u_asig=05VgVhNIzLPDHNnMYTEt2anq-DByFL568KESxXeL_3qvvb1cOf_zUfvnnYdityr7AZlLocTCvAXUH6StMqFRRSVqSxcTSkh8C0FCnyD593j_k50N8duSlrfQQQApm1Yhozv0y3ESyDWX-n4laIgPAy7LMMfY6LqtNJfDhi4KxrOcg7ozFsiUGsVAeSTqoZj3OT63Fl_12JOJ9D6CNoGHzLuVPChqJ45H8zfETAmI9FhFnGGoVpzW6QMhhSDbc5e_qWx7JHN_nWtA4lWCw6r1cmcxMGBWjTmEDMQKJ9PW6HWBE5v_rvt_8YTqQXP_TRcMqX3TbrNDfGSvQQXslQnDkz0zTXUT_zIvOVn_4BTwbi2CMNOtJ2Aq4b96o7yH-2uQ3D`添加到
https://github.com/notnotype/zhihuishu-cli/blob/c36145259b0f29bd1146c81e5a2f1d7d160a27e2/zhihuishu.py#L172
后，可以暂时解决问题。

后面打算使用selenium修复

**Comment by 19819068211** [comment]
经过修改zhihuishu.py中第172行内容，已经解决，可以登上了，谢谢

**Comment by 1738394450** [comment]
为啥我添加了还是未知错误啊

**Comment by 19819068211** [comment]
> 为啥我添加了还是未知错误啊

我是用浏览器登录之后显示的链接添加的

**Comment by 1738394450** [comment]
哦哦我去试试
