### ISSUE TITLE
请问如果想学习整个课程，应该执行什么命令，执行python zhihuishu-cli.py run-course 4c595b514d524258454a5858594d584a命令后找到mirai.config.json，请问参数填什么

### ISSUE THREAD

**Issue by 19819068211** [notnotype/zhihuishu-cli#4]
请问如果想学习整个课程，应该执行什么命令，执行python zhihuishu-cli.py run-course 4c595b514d524258454a5858594d584a命令后找到mirai.config.json，请问参数填什么
执行python zhihuishu-cli.py run-course 4c595b514d524258454a5858594d584a命令后
![1628399596735](https://user-images.githubusercontent.com/66981884/128621605-01cd0905-de16-437c-90fa-ff18655a8fd3.jpg)
找到文件并修改文件名后
![1628399654988](https://user-images.githubusercontent.com/66981884/128621629-8c378507-cb5b-41c5-849a-d226f7cf43d4.jpg)
文件内容为
![1628399697092](https://user-images.githubusercontent.com/66981884/128621639-517ee534-88a4-43a5-b8c9-a505598742ee.jpg)
host和auth_key不知道具体填什么，望大佬指教一下，谢谢

**Comment by notnotype** [comment]
需要另外部署mirai qq机器人
这是mirai-api-http的配置
https://github.com/project-mirai/mirai-api-http
