### ISSUE TITLE
关于"开始学习"这部分的代码

### ISSUE THREAD

**Issue by wdssfff00** [notnotype/zhihuishu-cli#5]
网上找一圈关于智慧树的   全是需要依赖浏览器的油猴
对zhihuishu-cli这种轻量终端项目真的感到惊艳
![屏幕截图 2021-09-02 210305](https://user-images.githubusercontent.com/83413772/131848660-b6511f5b-1e79-4d47-89f4-9ca8665cdd0e.png)
这个命令后面的1000219410是什么？
----个人以为是获取小课程列表获得的id，但是我的课程里没这么细分🤣很尴尬
![屏幕截图 2021-09-02 210659](https://user-images.githubusercontent.com/83413772/131849712-abed2656-344f-4825-9e64-14d1098c8d97.png)
只划分到小节，没划分到更细的小课程🤣
最终结果是输获取小课程列表的代码出现报错，然后输开始学习的代码也报错🤥

-------------另外大佬博客UI真不错，同样是二刺螈😆-----------------
![屏幕截图 2021-09-02 212054](https://user-images.githubusercontent.com/83413772/131851531-4964b7ea-01d0-44c1-8a96-478a022dc740.png)

**Comment by notnotype** [comment]
现在可以使用
```bash
python zhihuishu-cli.py study [recruitAndCourseId] [section_id]
```
来学习没有small lesson的课程了
